<?php

return [
    // Namespaces are being prefixed with the applications base namespace.
    /*
    |--------------------------------------------------------------------------
    | Namespaces
    |--------------------------------------------------------------------------
    | this array define the namespaces related to each file category generated by the
    | package, you can re-define these values to control under what namespace the
    | these files should reside.
    |
     */
    'namespaces' => [
        // Contracts (interfaces) base namespace
        'contracts' => 'Repositories\Contracts',
        // repository implementations classes namespace
        'repositories' => 'Repositories\Eloquent',
        // Criterions base namespace
        'criteria' => 'Repositories\Criteria',
    ],

    // Paths will be used with the `app()->basePath().'/app/'` function to reach app directory.
    /*
    |--------------------------------------------------------------------------
    | Paths
    |--------------------------------------------------------------------------
    | this array defines the path for each file category generated by the package,
    | you can re-define these values to control where the files should be stored,
    | by default they are stored in the application directory.
    |
     */
    'paths' => [
        'contracts' => 'Repositories/Contracts',
        'repositories' => 'Repositories/Eloquent',
        'criteria' => 'Repositories\Criteria',
    ],
];
