<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Base Values
    |--------------------------------------------------------------------------
    | this array give you the ability to define base path & namespace for package, path is
    | used to create the base directory in which all generated file are stored, on the
    | other hand, namespace is used to define the base namespace for those files.
    |
    | Note that the slash & anti-slash, for path & namespace respectively, are
    | required when defining these values.
    |
     */
    'base' => [
        // better choices are: 'app/' or root directory of the application
        'path' => storage_path('framework/testing/disks/app'),
        // better choice is: 'App\' the application base namespace
        'namespace' => app()->getNamespace(),
    ],

    /*
    |--------------------------------------------------------------------------
    | Namespaces
    |--------------------------------------------------------------------------
    | this array define the namespaces related to each file category generated by the
    | package, you can re-define these values to control under what namespace the
    | these files should reside.
    |
     */
    'namespaces' => [
        'contracts' => 'Repositories\Contracts',
        'implementations' => 'Repositories\Implementations',
        'criteria' => 'Repositories\Criteria',
    ],

    /*
    |--------------------------------------------------------------------------
    | Paths
    |--------------------------------------------------------------------------
    | this array defines the path for each file category generated by the package,
    | you can re-define these values to control where the files should be stored,
    | by default they are stored in the application directory.
    |
     */
    'paths' => [
        'contracts' => 'Repositories/Contracts',
        'implementations' => 'Repositories/Implementations',
        'criteria' => 'Repositories\Criteria',
    ],
];
